language: python
dist: xenial
sudo: true
env:
  global:
    -PIPENV_VENV_IN_PROJECT=1
    -PIPENV_IGNORE_VIRTUALENVS=1
python:
  - 3.9
install:
  - pip install pipenv
  - pipenv sync -d
script:
  - pipenv run flake8
  - pipenv run pytest